using SolidWorks.Interop.sldworks;
using SolidWorks.Interop.swconst;
using System;
using System.Collections.Generic;
using System.Linq;

namespace PDMLite
{
    public class ValidationResult
    {
        public bool IsValid => EmptyFields.Count == 0;
        public List<string> EmptyFields { get; set; } = new List<string>();
        public List<string> MissingFields { get; set; } = new List<string>();
    }

    public static class PropertyValidator
    {
        // Required properties (PartWeight is auto-filled so excluded).
        // PartType (Manufactured/Purchased) drives the assembly drawing-release
        // gate — Purchased parts with no drawing are skipped, Manufactured ones
        // are warned. Defaults to Manufactured in PropertyForm.
        public static readonly string[] RequiredProperties = new[]
        {
            "PartNo",
            "DrawingNo",
            "Description",
            "DrawnBy",
            "DrawnDate",
            "Material1",
            "FinishType",
            "Revision",
            "PartType"
        };

        // Check all required properties on the open document
        public static ValidationResult Validate(ModelDoc2 doc)
        {
            var result = new ValidationResult();
            // Drawings inherit properties from part — skip validation
            if (doc.GetType() == (int)swDocumentTypes_e.swDocDRAWING)
                return result;
            var cpm = doc.Extension.get_CustomPropertyManager(((SolidWorks.Interop.sldworks.Configuration)doc.GetActiveConfiguration()).Name);

            foreach (string propName in RequiredProperties)
            {
                string val = "", resolvedVal = "";
                bool retVal = cpm.Get4(propName, false, out val, out resolvedVal);

                if (!retVal)
                {
                    result.MissingFields.Add(propName);
                    result.EmptyFields.Add(propName);
                }
                else if (string.IsNullOrWhiteSpace(resolvedVal))
                {
                    result.EmptyFields.Add(propName);
                }
            }

            return result;
        }

        // Get a single property value
        public static string GetProperty(ModelDoc2 doc, string propName)
        {
            try
            {
                string configName = "";
                if (doc.GetType() != (int)swDocumentTypes_e.swDocDRAWING)
                {
                    var config = doc.GetActiveConfiguration()
                        as SolidWorks.Interop.sldworks.Configuration;
                    if (config != null) configName = config.Name;
                }
                var cpm = doc.Extension.get_CustomPropertyManager(configName);
                string val = "", resolvedVal = "";
                cpm.Get4(propName, false, out val, out resolvedVal);
                return resolvedVal ?? "";
            }
            catch { return ""; }
        }

        // Write a property value back to the document
        public static void SetProperty(ModelDoc2 doc, string propName, string value)
        {
            try
            {
                string configName = "";
                if (doc.GetType() != (int)swDocumentTypes_e.swDocDRAWING)
                {
                    var config = doc.GetActiveConfiguration()
                        as SolidWorks.Interop.sldworks.Configuration;
                    if (config != null) configName = config.Name;
                }
                var cpm = doc.Extension.get_CustomPropertyManager(configName);
                cpm.Add3(propName,
                         (int)swCustomInfoType_e.swCustomInfoText,
                         value,
                         (int)swCustomPropertyAddOption_e.swCustomPropertyReplaceValue);
            }
            catch { }
        }

        // Returns all configuration names in the document (parts/assemblies only).
        // For drawings returns an empty list — drawings have no configurations.
        public static List<string> GetConfigNames(ModelDoc2 doc)
        {
            var names = new List<string>();
            try
            {
                if (doc.GetType() == (int)swDocumentTypes_e.swDocDRAWING) return names;
                object raw = doc.GetConfigurationNames();
                string[] arr = raw as string[];
                if (arr != null)
                    foreach (string n in arr)
                        if (!IsAutoGeneratedConfig(n))
                            names.Add(n);
            }
            catch { }
            return names;
        }

        // SOLIDWORKS auto-creates a DERIVED flat-pattern configuration for sheet
        // metal parts, named "{parentConfig}SM-FLAT-PATTERN". It is NOT a config
        // the engineer manages — it inherits the parent config's custom properties
        // (same PartNo, DrawingNo, …). Enumerating it made a single-config sheet
        // metal part look MULTI-config: Rule 3.5 then saw two configs sharing a
        // PartNo and HARD-BLOCKED the save, and the multi-config release loop tried
        // to ShowConfiguration2 it and aborted (found in PR-52 testing). Filter it
        // out at this single enumeration chokepoint — config count, Rules 3/3.5/3.6,
        // the release/STEP loops and the per-config DB block all read through here,
        // so excluding it once keeps every consumer correct. The flat-pattern DXF
        // export is unaffected (it works off the active config's flat pattern via
        // the sheet-metal API, never by activating this config).
        public static bool IsAutoGeneratedConfig(string configName)
        {
            return !string.IsNullOrEmpty(configName) &&
                configName.EndsWith("SM-FLAT-PATTERN",
                    StringComparison.OrdinalIgnoreCase);
        }

        // Read a single property from a specific named configuration.
        // Useful when the caller knows which config to target (e.g. during
        // multi-config save or per-config revision bump).
        public static string GetProperty(ModelDoc2 doc, string propName,
            string configName)
        {
            try
            {
                var cpm = doc.Extension.get_CustomPropertyManager(configName ?? "");
                string val = "", resolvedVal = "";
                cpm.Get4(propName, false, out val, out resolvedVal);
                return resolvedVal ?? "";
            }
            catch { return ""; }
        }

        // Write a property to a specific named configuration.
        public static void SetProperty(ModelDoc2 doc, string propName,
            string value, string configName)
        {
            try
            {
                var cpm = doc.Extension.get_CustomPropertyManager(configName ?? "");
                cpm.Add3(propName,
                         (int)swCustomInfoType_e.swCustomInfoText,
                         value,
                         (int)swCustomPropertyAddOption_e.swCustomPropertyReplaceValue);
            }
            catch { }
        }

        // Validate all configurations and return a dictionary of
        //   configName → list of missing/empty required field names
        // for every config that has at least one problem. An empty dict means
        // all configurations are complete. Only call on parts/assemblies.
        public static Dictionary<string, List<string>> ValidateAllConfigs(ModelDoc2 doc)
        {
            var result = new Dictionary<string, List<string>>(
                StringComparer.OrdinalIgnoreCase);
            try
            {
                if (doc.GetType() == (int)swDocumentTypes_e.swDocDRAWING)
                    return result;

                foreach (string cfgName in GetConfigNames(doc))
                {
                    var missing = new List<string>();
                    var cpm = doc.Extension.get_CustomPropertyManager(cfgName);
                    foreach (string propName in RequiredProperties)
                    {
                        string val = "", resolvedVal = "";
                        bool ok = cpm.Get4(propName, false, out val, out resolvedVal);
                        if (!ok || string.IsNullOrWhiteSpace(resolvedVal))
                            missing.Add(propName);
                    }
                    if (missing.Count > 0)
                        result[cfgName] = missing;
                }
            }
            catch { }
            return result;
        }

        // Auto-calculate PartWeight from SOLIDWORKS mass properties
        public static void AutoFillWeight(ModelDoc2 doc)
        {
            try
            {
                int docType = doc.GetType();
                if (docType != (int)swDocumentTypes_e.swDocPART &&
                    docType != (int)swDocumentTypes_e.swDocASSEMBLY)
                    return;

                int status;
                MassProperty mp = doc.Extension.GetMassProperties2(1, out status, false);

                if (mp == null) return;

                double massKg = mp.Mass;
                double massLbs = massKg * 2.20462;

                string weightStr = $"{massKg:F3} kg / {massLbs:F3} lbs";
                SetProperty(doc, "PartWeight", weightStr);
            }
            catch
            {
                // Non-fatal — skip if mass properties unavailable
            }
        }
        // Convert date properties from yyyy-MM-dd to MM/dd/yyyy format
        public static void FixDateFormats(ModelDoc2 doc)
        {
            try
            {
                string[] dateProps = { "DrawnDate", "CheckedDate" };
                foreach (string prop in dateProps)
                {
                    string val = GetProperty(doc, prop);
                    if (string.IsNullOrEmpty(val)) continue;

                    // Check if in old yyyy-MM-dd format
                    if (DateTime.TryParseExact(val, "yyyy-MM-dd",
                        null, System.Globalization.DateTimeStyles.None,
                        out DateTime dt))
                    {
                        // Convert to new format
                        SetProperty(doc, prop, dt.ToString("MM/dd/yyyy"));
                    }
                }
            }
            catch { }
        }
    }

}